### ISSUE TITLE
Any plans to upgrade this to Webpack 3?

### ISSUE THREAD

**Issue by Inlesco** [mihap/webpack-react-hot-bolerplate#6]
FEATURE REQUEST.

As this is a nice starter kit, I'd love to see it being updated with the newest and most effective toolset available on the market.

Thus, Webpack 3. 

Are there any plans for this upgrade? ;)

**Comment by mihap** [comment]
Yes, I plan to update this weekend.
webpack 3, react 16 and babel 7
